### ISSUE TITLE
Loglar Çok Alakasız

### ISSUE THREAD

**Issue by borkluce** [rburaksaritas/tcdd-bilet-bulucu-web#2]
Selamlar. Şu şekilde loglar alıyorum:
![image](https://github.com/user-attachments/assets/41db4b58-2f7f-4842-9ab2-98cbf42671cd)

Oysa gerçeği yansıtmıyor. Gördüğünüz gibi o tren seferi tamamen dolu:
![image](https://github.com/user-attachments/assets/e7ebdd4a-d589-4a30-9a50-9e975e3cd5ce)

**Comment by borkluce** [comment]
Şimdi fark ettim de dolu gözükse bile üzerine tıklayınca gerçekten yer olabiliyor. Afedersin. 
Ayrıca bu bot sayesinde bilet bulabildim, çok teşekkürler.

**Comment by rburaksaritas** [comment]
Rica ederim :)
